### ISSUE TITLE
Contact links from .about.yml/Team API

### ISSUE THREAD

**Issue by mbland** [18F/dashboard#254]
Hey @gboone, you'd mentioned being cool with just getting the data for the `contacts:` field from the Team API and posting it straight into the template, rather than parsing it as an email address or as a GitHub URL fragment as we do now. Would you want to have just a raw URL (`mailto:` or `https:` that you'd post as `<a href="{{ contact_url }}">{{ contact_url }}</a>`, or have an object with `url:` and `text:` fields that you'd render as `<a href="{{ contact.url }}">{{ contact.text }}</>`?

cc: @monfresh re: 18F/github-dashing#24

**Comment by gboone** [comment]
Probably `contact.url` and `contact.text` I think.

```
---
contact:
  url: https://blah.blah/blah
  text: Black blah blah
```

something like that. That seems more extensible for the future, anyway.

**Comment by mbland** [comment]
Sounds good to me.

cc: @melodykramer @jeremiak

**Comment by DavidEBest** [comment]
This is how a fully specified contact field looks on staging:
<img width="885" alt="screenshot 2015-10-05 12 06 35" src="https://cloud.githubusercontent.com/assets/933586/10286104/14ea861e-6b5a-11e5-82ec-64e5820400c4.png">

That is based on the following format:

```
contact:
- url: mailto:michael.bland@acm.org
  text: Mike Bland
- url: https://github.com/18F/hmac-authentication-npm/issues
  text: 18F/hmac-authentication-npm issues
```

Is that the expected format? If so, I'd be happy to submit a fix.
